// Typed access to the generated content in ./content/*.json.
//
// Both files are produced by scripts/import-content.mjs from luciancs.nl and
// committed, so the site builds and serves without the WordPress install being
// reachable. Nothing here talks to the network.
import { iconNames, type IconName } from "@/components/icons"
import pagesJson from "@/content/pages.json"
import siteJson from "@/content/site.json"

export type Inline =
  | { t: "text"; v: string }
  | { t: "br" }
  | { t: "span"; marks: Mark[]; c: Inline[] }
  | { t: "link"; href: string; c: Inline[]; button?: true; external?: true }

export type Mark = "strong" | "em" | "underline" | "accent" | "muted"

export type Block =
  | {
      t: "heading"
      level: 1 | 2 | 3 | 4
      accent: boolean
      size?: number
      strong?: boolean
      align?: "center"
      c: Inline[]
    }
  | { t: "paragraph"; c: Inline[]; align?: "center" }
  | { t: "list"; ordered: boolean; c: Inline[][] }
  | { t: "divider"; accent: boolean }
  | { t: "contactForm" }

export type ServiceCard = {
  title: string
  lead: Inline[]
  href: string
  icon: IconName
  items: string[]
}

export type Testimonial = { quote: string; name: string; role: string }

export type Section =
  | { t: "prose"; variant: "article" | "bare"; width: "text" | "wide"; blocks: Block[] }
  | { t: "banner"; heading: string }
  | { t: "services"; cards: ServiceCard[] }
  | { t: "testimonials"; items: Testimonial[] }

export type Page = {
  id: number
  path: string
  title: string
  description: string
  sections: Section[]
}

export type FooterColumn = { title: string; lines: Inline[][] }
export type SocialName = "facebook" | "linkedin" | "twitter"
export type Social = { name: SocialName; href: string }

export type Site = {
  brand: string
  heroHeading: string
  nav: { label: string; href: string }[]
  columns: FooterColumn[]
  social: Social[]
  contact: {
    name: string
    street: string
    postalCode: string
    city: string
    email: string
    phone: string
    phoneHref: string
  }
}

/** The importer only emits icon names it can prove exist in icons.tsx; this
 *  keeps that promise visible in the type system instead of trusting a cast. */
const isIconName = (value: string): value is IconName => (iconNames as string[]).includes(value)

const normalise = (pages: Page[]): Page[] =>
  pages.map((page) => ({
    ...page,
    sections: page.sections.map((section) =>
      section.t === "services"
        ? {
            ...section,
            cards: section.cards.map((card) => {
              if (!isIconName(card.icon)) {
                throw new Error(`unknown icon "${card.icon}" on ${page.path} - re-run the import`)
              }
              return card
            }),
          }
        : section,
    ),
  }))

// The JSON is generated by scripts/import-content.mjs, which fails the import
// rather than emit anything that does not satisfy these shapes. TypeScript
// cannot see that across a .json import, so the boundary is asserted once here.
export const pages: Page[] = normalise(pagesJson.pages as unknown as Page[])

export const site: Site = siteJson as unknown as Site

export const pagesByPath: Record<string, Page> = Object.fromEntries(
  pages.map((page) => [page.path, page]),
)

/** Old WordPress shortlinks (`/index.html?p=7`) still resolve, page id to path. */
export const pathByWpId: Record<string, string> = Object.fromEntries(
  pages.map((page) => [String(page.id), page.path]),
)

/**
 * Structured data for search engines.
 *
 * The WordPress site carried Rank Math's AccountingService markup, and the
 * rebuild dropped it; this restores the parts we can state without inventing
 * anything - name, address, phone, e-mail and the profiles already in the
 * footer. Opening hours and prices are left out because nobody has told us
 * what they are.
 *
 * The URL is the domain the site will live on. The preview is noindex, so this
 * only starts working when it moves there.
 */
export const structuredData = {
  "@context": "https://schema.org",
  "@type": "AccountingService",
  name: site.brand,
  url: "https://www.luciancs.nl/",
  email: site.contact.email,
  telephone: `+31${site.contact.phoneHref.replace(/^tel:0?/, "")}`,
  address: {
    "@type": "PostalAddress",
    streetAddress: site.contact.street,
    postalCode: site.contact.postalCode,
    addressLocality: site.contact.city,
    addressCountry: "NL",
  },
  areaServed: { "@type": "City", name: site.contact.city },
  sameAs: site.social.map((profile) => profile.href),
}

export const homePage = pagesByPath["/"]
if (!homePage) throw new Error("content/pages.json has no '/' page")

const navLabelByPath: Record<string, string> = Object.fromEntries(
  site.nav.map((item) => [item.href, item.label]),
)

/** WordPress SEO titles ("Boekhouder Winschoten | LUCIAN") cut back to the name. */
export function shortTitle(title: string): string {
  const short = title.replace(/^LUCIAN\s*:\s*/i, "").replace(/\s*[|–—-]\s*LUCIAN\b.*$/i, "").trim()
  return short || title
}

/**
 * Several pages title themselves "Name: a longer promise"; the name is enough.
 * One heading is "Kenniscentrum > Administratie", and a ">" inside a crumb
 * reads as a breadcrumb separator, so it is spelled out.
 */
const namePart = (text: string) =>
  text.split(/[:|]/)[0].replace(/\s*>\s*/g, " \u00b7 ").trim() || text

function ownHeading(page: Page): string | undefined {
  for (const section of page.sections) {
    if (section.t !== "prose") continue
    for (const block of section.blocks) {
      if (block.t === "heading" && block.level === 1) {
        const text = block.c.map((node) => ("v" in node ? node.v : "")).join("").trim()
        if (text) return text
      }
    }
  }
  return undefined
}

/**
 * Breadcrumb labels, in the order the site itself would say them: the menu's own
 * word if the page is in the menu, otherwise the page's heading, otherwise the
 * cleaned SEO title. Nothing is truncated - two of these run to 57 characters
 * and mangling a name to fit a rail is worse than letting it wrap.
 */
export function labelFor(path: string): string {
  const fromNav = navLabelByPath[path]
  if (fromNav) return fromNav
  const page = pagesByPath[path]
  if (!page) {
    const last = path.split("/").filter(Boolean).at(-1) ?? ""
    return last.replace(/\.html$/, "").replace(/-/g, " ")
  }
  const heading = ownHeading(page)
  return namePart(heading ?? shortTitle(page.title))
}

export type Crumb = { label: string; href: string }

/** Breadcrumb trail derived from the URL, using the labels the menu uses. */
export function crumbsFor(path: string): Crumb[] {
  const crumbs: Crumb[] = [{ label: site.brand, href: "/" }]
  let prefix = ""
  for (const segment of path.replace(/^\//, "").replace(/\.html$/, "").split("/").filter(Boolean)) {
    prefix += `/${segment}`
    const asPage = `${prefix}.html`
    const href = pagesByPath[asPage] ? asPage : prefix
    crumbs.push({ label: labelFor(href), href })
  }
  return crumbs
}

/** Most pages open with their own h1 in the article; a few have no body at all. */
export function hasOwnTitle(page: Page): boolean {
  return page.sections.some(
    (section) =>
      section.t === "prose" &&
      section.blocks.some((block) => block.t === "heading" && block.level === 1),
  )
}
