import { crumbsFor, site, type Page } from "@/lib/content"

/**
 * The domain this site will live on, used for canonicals, Open Graph URLs and
 * structured data. The preview host is noindex, so these only start doing work
 * when the site moves to the client's own domain - but they have to be right
 * *before* the move, not after.
 */
export const ORIGIN = site.canonicalOrigin

export const canonicalFor = (path: string) => (path === "/" ? `${ORIGIN}/` : `${ORIGIN}${path}`)

// A 1200x630 crop of the same photograph the hero uses, generated by the import
// (Open Graph images want JPEG or PNG, and most scrapers cannot read AVIF).
export const OG_IMAGE = `${ORIGIN}/media/og.jpg`

export type Faq = { question: string; answer: string }

/**
 * Q&A pairs a page shows, for FAQPage markup.
 *
 * Strict on purpose: only a heading that says "veelgestelde vragen" followed by
 * a list, whose items start with a bold sentence ending in a question mark.
 * Anything that does not match that shape is skipped rather than guessed at -
 * marking up something that is not a question gets the page penalised.
 */
export function faqsFor(page: Page): Faq[] {
  const faqs: Faq[] = []
  for (const section of page.sections) {
    if (section.t !== "prose") continue
    section.blocks.forEach((block, index) => {
      if (block.t !== "heading") return
      const heading = block.c.map((node) => ("v" in node ? node.v : "")).join("")
      if (!/veelgestelde\s+vragen|^faq/i.test(heading)) return
      const next = section.blocks[index + 1]
      if (next?.t !== "list") return
      for (const item of next.c) {
        const [first, ...rest] = item
        if (first?.t !== "span" || !first.marks.includes("strong")) continue
        const question = first.c.map((node) => ("v" in node ? node.v : "")).join("").trim()
        const answer = rest.map((node) => ("v" in node ? node.v : "")).join("").trim()
        if (!question.endsWith("?") || answer.length < 20) continue
        faqs.push({ question, answer: answer.replace(/^:\s*/, "") })
      }
    })
  }
  return faqs
}

/**
 * One `@graph` per page: the business, the page itself, where it sits in the
 * site, and its questions if it has any. Everything here comes from the import -
 * no opening hours, prices or ratings are claimed, because nobody has told us
 * what they are.
 */
export function structuredDataFor(page: Page) {
  const organisation = {
    "@type": "AccountingService",
    "@id": `${ORIGIN}/#organisatie`,
    name: site.brand,
    url: `${ORIGIN}/`,
    email: site.contact.email,
    telephone: `+31${site.contact.phoneHref.replace(/^tel:0?/, "")}`,
    address: {
      "@type": "PostalAddress",
      streetAddress: site.contact.street,
      postalCode: site.contact.postalCode,
      addressLocality: site.contact.city,
      addressCountry: "NL",
    },
    areaServed: { "@type": "City", name: site.contact.city },
    sameAs: site.social.map((profile) => profile.href),
  }

  // The four service lines the homepage lists, as an offer catalogue - only on
  // the page that actually shows them.
  const offers = page.sections
    .filter((section) => section.t === "services")
    .flatMap((section) =>
      section.cards.map((card) => ({
        "@type": "Offer",
        itemOffered: {
          "@type": "Service",
          name: card.title,
          description: card.lead.map((node) => ("v" in node ? node.v : "")).join(""),
          url: canonicalFor(card.href),
        },
      })),
    )
  if (offers.length) {
    Object.assign(organisation, {
      hasOfferCatalog: {
        "@type": "OfferCatalog",
        name: "Diensten",
        itemListElement: offers,
      },
    })
  }

  const graph: object[] = [
    organisation,
    {
      "@type": "WebPage",
      "@id": canonicalFor(page.path),
      url: canonicalFor(page.path),
      name: page.title,
      description: page.description || undefined,
      inLanguage: "nl-NL",
      isPartOf: { "@type": "WebSite", "@id": `${ORIGIN}/#website`, name: site.brand, url: `${ORIGIN}/` },
      about: { "@id": `${ORIGIN}/#organisatie` },
    },
  ]

  const crumbs = crumbsFor(page.path).filter((crumb) => crumb.label !== site.brand || crumb.href === "/")
  if (page.path !== "/" && crumbs.length > 1) {
    graph.push({
      "@type": "BreadcrumbList",
      itemListElement: crumbs.map((crumb, index) => ({
        "@type": "ListItem",
        position: index + 1,
        name: crumb.label,
        item: canonicalFor(crumb.href),
      })),
    })
  }

  const faqs = faqsFor(page)
  if (faqs.length) {
    graph.push({
      "@type": "FAQPage",
      mainEntity: faqs.map((faq) => ({
        "@type": "Question",
        name: faq.question,
        acceptedAnswer: { "@type": "Answer", text: faq.answer },
      })),
    })
  }

  return { "@context": "https://schema.org", "@graph": graph }
}
